/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * autonomousExecutionLoop.ts -- Phase 28: Unified Autonomous Execution Loop
 *
 * This is the single service that replaces the previous fragmented services:
 *   - ExecutionGraph
 *   - AIExecution
 *   - AgentOrchestrator
 *   - ExecutionSandbox (coordination layer)
 *   - AutonomousExecution (old Phase 25)
 *   - MultiAgentExecution
 *
 * The loop lifecycle: Planning -> Executing -> Verifying -> Repairing -> Committing
 * With crash recovery, checkpoint/rollback, and repair statistics tracking.
 *
 * Every method in the browser service implementation produces real output.
 * No placeholder methods. No simulated intelligence. No vague abstractions.
 */

import { createDecorator } from '../../../../platform/instantiation/common/instantiation.js';
import { Event } from '../../../../base/common/event.js';

// ─── Enumerations ───────────────────────────────────────────────────────────────

/**
 * Top-level states of the autonomous execution loop.
 * The loop transitions through these states as it processes milestones.
 */
export enum LoopState {
        Idle = 'idle',
        Planning = 'planning',
        Executing = 'executing',
        Verifying = 'verifying',
        Repairing = 'repairing',
        Committing = 'committing',
        Paused = 'paused',
        Stopped = 'stopped',
        Crashed = 'crashed',
        Recovering = 'recovering'
}

/**
 * Status of an individual milestone within an execution plan.
 */
export enum MilestoneStatus {
        Pending = 'pending',
        InProgress = 'inProgress',
        Verifying = 'verifying',
        Repairing = 'repairing',
        Completed = 'completed',
        Failed = 'failed',
        Skipped = 'skipped'
}

// ─── Data Types ─────────────────────────────────────────────────────────────────

/**
 * A single step within a milestone. Each step has an action type that
 * determines which handler the loop dispatches to.
 */
export interface ExecutionStep {
        id: string;
        milestoneId: string;
        description: string;
        action: 'edit' | 'command' | 'git' | 'llm' | 'verify';
        params: Record<string, any>;
        status: 'pending' | 'running' | 'completed' | 'failed' | 'skipped';
        result?: any;
        error?: string;
        retryCount: number;
        maxRetries: number;
}

/**
 * A milestone within the execution plan. Contains ordered steps and
 * tracks its own status, timing, checkpoint commit hash, and repair attempts.
 */
export interface Milestone {
        id: string;
        name: string;
        description: string;
        steps: ExecutionStep[];
        status: MilestoneStatus;
        startedAt?: number;
        completedAt?: number;
        checkpointCommitHash?: string;
        repairAttempts: number;
}

/**
 * The full execution plan, generated by the LLM from a project idea.
 * Contains all milestones, the current loop state, and cumulative metrics.
 */
export interface ExecutionPlan {
        id: string;
        projectName: string;
        idea: string;
        constraints: string[];
        milestones: Milestone[];
        state: LoopState;
        createdAt: number;
        updatedAt: number;
        currentMilestoneIndex: number;
        currentStepIndex: number;
        totalTokensUsed: number;
        totalCost: number;
}

/**
 * Record of a single repair attempt. Tracks the full context of what
 * went wrong, what the LLM suggested, what was applied, and whether
 * the result improved, worsened, or had no effect.
 */
export interface RepairAttempt {
        milestoneId: string;
        stepId: string;
        failureOutput: string;
        llmPrompt: string;
        llmResponse: string;
        patchApplied: string;
        verificationResult: 'passed' | 'failed' | 'worse';
        rolledBack: boolean;
        timestamp: number;
}

/**
 * Crash recovery state persisted to IStorageService after every step.
 * Allows the loop to resume from the last checkpoint after a crash.
 */
export interface CrashRecoveryState {
        planId: string;
        state: LoopState;
        currentMilestoneIndex: number;
        currentStepIndex: number;
        lastCheckpointHash: string;
        activeRepairs: RepairAttempt[];
        pendingVerification: boolean;
        savedAt: number;
}

// NOTE: ITerminalExecutionBridgeService is defined in ./terminalExecutionBridge.ts
// and is imported by the browser service directly from that module.

// ─── Execution Events ───────────────────────────────────────────────────────────

/**
 * Event types emitted by the autonomous execution loop for the UI stream.
 */
export enum ExecutionEventType {
        LoopStarted = 'loop-started',
        LoopPaused = 'loop-paused',
        LoopResumed = 'loop-resumed',
        LoopStopped = 'loop-stopped',
        LoopCompleted = 'loop-completed',
        LoopCrashed = 'loop-crashed',
        LoopRecovered = 'loop-recovered',
        StateChanged = 'state-changed',
        MilestoneStarted = 'milestone-started',
        MilestoneCompleted = 'milestone-completed',
        MilestoneFailed = 'milestone-failed',
        StepStarted = 'step-started',
        StepCompleted = 'step-completed',
        StepFailed = 'step-failed',
        VerificationStarted = 'verification-started',
        VerificationPassed = 'verification-passed',
        VerificationFailed = 'verification-failed',
        RepairStarted = 'repair-started',
        RepairApplied = 'repair-applied',
        RepairFailed = 'repair-failed',
        RollbackPerformed = 'rollback-performed',
        CheckpointCreated = 'checkpoint-created',
        PlanCreated = 'plan-created',
        Error = 'error'
}

/**
 * An event emitted by the autonomous execution loop.
 * Carries the event type, a human-readable message, structured data,
 * and the timestamp.
 */
export interface ExecutionEvent {
        readonly type: ExecutionEventType;
        readonly message: string;
        readonly data: Record<string, unknown>;
        readonly timestamp: number;
}

// ─── Service Interface ──────────────────────────────────────────────────────────

/**
 * IAutonomousExecutionLoopService -- The unified autonomous execution loop.
 *
 * Replaces the previous fragmented services with a single coherent loop
 * that handles planning, execution, verification, repair, checkpointing,
 * and crash recovery.
 *
 * REAL responsibilities:
 *   - Generate execution plans from project ideas via LLM
 *   - Execute steps in order, dispatching to the correct handler
 *   - Verify milestones after all steps complete
 *   - Repair failures by sending error context to the LLM and applying fixes
 *   - Rollback worsening repairs via git checkpoint commits
 *   - Track repair statistics (success rate, rollback frequency, etc.)
 *   - Persist crash recovery state after every step
 *   - Resume from crash recovery on startup
 *
 * HONEST limitations:
 *   - LLM-generated plans are only as good as the LLM's understanding
 *   - Repair success depends on LLM capability, not on this service
 *   - Verification runs real build/lint/typecheck, but passing != correct
 *   - Crash recovery depends on IStorageService reliability
 *   - Git operations depend on the git extension and a valid repository
 */
export interface IAutonomousExecutionLoopService {
        readonly _serviceBrand: undefined;

        /** Fired when the loop state changes. */
        readonly onStateChange: Event<LoopState>;
        /** Fired when a milestone is updated (status change, step completion, etc.). */
        readonly onMilestoneUpdate: Event<Milestone>;
        /** Fired when a step is updated (status change, result available, etc.). */
        readonly onStepUpdate: Event<ExecutionStep>;
        /** Fired when a repair attempt is recorded. */
        readonly onRepairAttempt: Event<RepairAttempt>;
        /** Fired when an execution event occurs (for the UI stream). */
        readonly onExecutionEvent: Event<ExecutionEvent>;

        // ─── Plan management ────────────────────────────────────────────────────────

        /**
         * Create a new execution plan by sending the project idea and constraints
         * to the LLM, then parsing the response into an ExecutionPlan with
         * milestones and steps.
         */
        createPlan(projectName: string, idea: string, constraints: string[]): Promise<ExecutionPlan>;

        /**
         * Load a previously saved plan from storage by its ID.
         * Returns null if the plan does not exist.
         */
        loadPlan(planId: string): Promise<ExecutionPlan | null>;

        /**
         * Get the currently active plan, or null if no plan is loaded.
         */
        getCurrentPlan(): ExecutionPlan | null;

        // ─── Loop control ───────────────────────────────────────────────────────────

        /**
         * Start the autonomous execution loop for the given plan.
         * Validates the plan, sets state to Executing, and begins _runLoop().
         * Throws if a loop is already running.
         */
        start(plan: ExecutionPlan): Promise<void>;

        /**
         * Pause the loop at the next iteration boundary.
         * The loop checks the _cancelled flag and exits gracefully.
         */
        pause(): void;

        /**
         * Resume the loop from the Paused state.
         * Resets the _cancelled flag and re-enters _runLoop().
         */
        resume(): void;

        /**
         * Stop the loop permanently. Sets the _cancelled flag.
         * The loop transitions to Stopped at the next iteration.
         */
        stop(): void;

        /**
         * Retry the current step that failed.
         * Resets the step status to pending and re-executes.
         */
        retryCurrentStep(): Promise<void>;

        /**
         * Rollback to the last checkpoint commit.
         * Returns true if the rollback succeeded, false otherwise.
         */
        rollbackToLastCheckpoint(): Promise<boolean>;

        // ─── State queries ──────────────────────────────────────────────────────────

        /** Get the current loop state. */
        getState(): LoopState;

        /** Get the current milestone being processed, or null. */
        getCurrentMilestone(): Milestone | null;

        /** Get the current step being processed, or null. */
        getCurrentStep(): ExecutionStep | null;

        /** Get progress counts for milestones and steps. */
        getProgress(): { milestones: number; steps: number; completedMilestones: number; completedSteps: number };

        // ─── Repair statistics ──────────────────────────────────────────────────────

        /**
         * Get aggregate repair statistics.
         * - totalAttempts: total number of repair attempts across all milestones
         * - successRate: fraction of repairs that passed verification
         * - rollbackFrequency: fraction of repairs that required rollback
         * - worseningFrequency: fraction of repairs that made things worse
         * - averageAttempts: average number of repair attempts per milestone
         */
        getRepairStats(): { totalAttempts: number; successRate: number; rollbackFrequency: number; worseningFrequency: number; averageAttempts: number };

        // ─── Crash recovery ─────────────────────────────────────────────────────────

        /** Save the current execution state to IStorageService for crash recovery. */
        saveCrashRecoveryState(): void;

        /**
         * Restore execution state from IStorageService after a crash.
         * Returns true if a valid recovery state was found and loaded.
         */
        restoreCrashRecoveryState(): Promise<boolean>;

        /** Check whether a crash recovery state exists in storage. */
        hasCrashRecoveryState(): boolean;

        /** Clear any stored crash recovery state. */
        clearCrashRecoveryState(): void;
}

// ─── Service Decorator ──────────────────────────────────────────────────────────

export const IAutonomousExecutionLoopService = createDecorator<IAutonomousExecutionLoopService>('autonomousExecutionLoopService');
